# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ced51b76f11c02a177a0d171dd86cbace3d0c352855ca888f14c72ff9af4f4f7833210a5de834985e8bc8a667cb433d15a03ca092815b13356fbd28e16e20537

test:
  secret_key_base: 0aa0a80e683dceb981b4a1e964a2dccb3118b5a1aab080f71d38d89c4741254b426cd599d53f2076dcb35589cb2e895ad8d00613fbc83d3dac7799e2128e14e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
